### ISSUE TITLE
Use header Zoom icon instead of generic "camera" icon

### ISSUE THREAD

**Issue by cadavre** [mattermost/mattermost-plugin-zoom#102]
Hi, some of use are using more that one audio-video communicator. It is hard to distinguish them by looking at the icon of generic camera.

My suggestion is to create Mattermost-style icon for Zoom and use it instead.

<img width="52" alt="Zrzut ekranu 2020-04-16 o 10 04 10" src="https://user-images.githubusercontent.com/461796/79430738-afa1ec00-7fc9-11ea-81a8-8f5afdee6fb8.png">

**Comment by levb** [comment]
we also needs one for WebEx

**Comment by asaadmahmood** [comment]
Does make sense.
Here's an svg.
I did not provide a solid svg of the shape, because I wasn't sure if using the inner shape would be okay with zoom. So we can just use the profile image we have.
I may have to add UI adjustments on the webapp so images are displayed correctly, so that should go in before this update.

[zoom.svg.zip](https://github.com/mattermost/mattermost-plugin-zoom/files/4510323/zoom.svg.zip)

**Comment by cadavre** [comment]
@asaadmahmood looks good! I haven't found any public Zoom visual identity usage guide, but I think that full version of yours will be actually better than outlined version.
