### ISSUE TITLE
Master branch is showing a lint error

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-zoom#168]
When I run the full `make` I see some type of linting error

```
Running golangci-lint
golangci-lint run ./...
server/command.go:129:10: wrapperFunc: use strings.ReplaceAll method in `strings.Replace(helpText, "|", "`", -1)` (gocritic)
	text += strings.Replace(helpText, "|", "`", -1)
	        ^
server/command.go:132:18: wrapperFunc: use strings.ReplaceAll method in `strings.Replace(oAuthHelpText, "|", "`", -1)` (gocritic)
		text += "\n" + strings.Replace(oAuthHelpText, "|", "`", -1)
		               ^
make: *** [golangci-lint] Error 1
```

Steps:
- Get latest from master `commit 971b02c`
- run `make` 

**Observed**: Some type of lint error

**Comment by hanzei** [comment]
This doesn't happen in CI. Making it a HW.

**Comment by srgyrn** [comment]
> This doesn't happen in CI. Making it a HW.

It doesn't happen in CI because CI uses golangci-lint@1.24.0 which uses gocritic@0.4.1. The wrapperFunc_checker -which gives the mentioned warning- has been marked as stable and [removed being an _experimental_ feature in gocritic@0.5.2](https://github.com/go-critic/go-critic/commit/9213f6f2fc30514061313d0ddbd5177c47322d8b#diff-d1d1cae38b98bf81d0fdb78b508d7bf9). The gocritic version has been upgraded to 0.5.2 in [golangci-lint@1.31.0](https://github.com/golangci/golangci-lint/commit/6ac41d9f338d883f6dee24ad6253f68bd60f3da0#diff-37aff102a57d3d7b797f152915a6dc16R12). 

The warning makes sense since all the occurrences are expected to be replaced (n is set to be -1) so why not use ReplaceAll instead of Replace :)

I also want to raise attention to the return values of the runHelpCommand method. The signature says it may return errors but it only and always returns a fixed nil value.
