### ISSUE TITLE
zoom meeting message is not edited.

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-plugin-zoom#240]
https://user-images.githubusercontent.com/89907719/141179728-505df1ec-1267-4454-97fa-e5926bece3da.mp4

**Comment by sibasankarnayak** [comment]
@mickmister @hanzei  
i was just looking into the issue , need some help it seems more like editing a post and it is a part of mm-server/mm-webapp
1. can a post can be edited ?

**Comment by sibasankarnayak** [comment]
> @sibasankarnayak What's your current goal, what have you tried so far, and what is happening instead of your intended result?
> 
> You can edit your own posts, and since the plugin makes the post on your behalf, that's your post. You should see an "Edit" option in the "dot menu" when you hover over the post.

@mickmister the current goal is to edit the message i have started a meeting once i start a zoom meeting but currently we are not able to do so after edit i still see the previous default message

i was checking the code and seems we are having this edit message logic in mm-server , so was not sure that we were able to edit a post

**Comment by larkox** [comment]
The reason we "cannot edit the message" is because it is a custom post. The rendering is not using the message itself, it is rendering what the plugin says to render.

The message is still useful since it is what will show when the plugin gets disabled or the user is looking from the mobile App. And it is probably being updated.

One approach to "fix" this, is to use the message on the post to render the text, instead of rendering a predefined text.

**Comment by mickmister** [comment]
@sibasankarnayak Please see the comment above

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-plugin-zoom/pull/248 should be used as a starting point
