### ISSUE TITLE
The previous posts for updating the settings should get deleted once the user runs the settings slash command again.

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-zoom#395]
While testing this plugin, I found an issue regarding the settings slash command.
If the user runs the settings slash command multiple times, multiple posts are presented to the user with all the options available. In this way, user can select different options in 2 different posts.
So, the selection does not depend on the latest post in the channel but on the latest option selected by the user which can be of any previous post.

I am attaching screenshots for the same:-

**Multiple posts:-**
![image](https://github.com/user-attachments/assets/845d19c4-c7c1-44c2-a556-eda4852d1a79)

**Actual value stored:-**
![image](https://github.com/user-attachments/assets/ab5ae762-9af9-415c-8a67-130b458312a6)

In the screenshots above, it is clearly visible that in the last post, the user choose "No", but the value stored is "Yes", since the first post was the latest on which user took any action.

**Possible solution:-** You can delete the previous posts once the user runs the settings slash command.
Note:- For more information, you can refer to mscalendar plugin.

**Comment by Kshitij-Katiyar** [comment]
@AayushChaudhary0001 Currently, the settings are configured as ephemeral posts, which are removed upon refresh and are user-specific rather than server-wide. As the setting posts are ephemeral, the user can easily remember the last setting he has chosen. Given the nature of these settings, the effort required to implement this change may not justify the benefits. I would appreciate your thoughts on this.

One potential solution is to convert the settings post from an ephemeral message to a standard one and redirect the user to the Zoom bot's direct message channel, where the settings post can be delivered.

**Comment by AayushChaudhary0001** [comment]
@Kshitij-Katiyar If changing the post from an ephemeral message to a standard post and redirecting the user to the Zoom bot's account is the solution, then I think there is no benefit of doing this. Since it would be a very lengthy task and a this issue is not a blocker, we can keep it as it is.
