### ISSUE TITLE
Feature request: change meeting ID when users call meeting

### ISSUE THREAD

**Issue by hyoputer** [mattermost/mattermost-plugin-zoom#81]
It would be nice if users could change meeting ID or apply password when they call meeting.

Links of my meetings are always same even in different teams so people who have past meeting links could come to my meeting.

thanks!

**Comment by ThiefMaster** [comment]
Creating a new meeting instead of using the personal meeting id would indeed make sense.

**Comment by hyoputer** [comment]
@ThiefMaster If I use
![capture](https://user-images.githubusercontent.com/19164087/77298657-95f4e800-6d2e-11ea-834f-955b19a1b02a.PNG)

"this" icon the new meeting always use my personal ID.
Do you have any alternatives?

**Comment by ThiefMaster** [comment]
Not sure what you are trying to tell me. I know that it uses the personal ID and my comment was suggesting that the plugin should indeed have an option to create new meetings instead of doing that.

**Comment by hyoputer** [comment]
Oh, sorry. I've been misunderstood

**Comment by codemakeshare** [comment]
Great suggestion, I would also appreciate this. Just tried out the plugin, and had the same thought.

A related suggestion: if this feature would be implemented (to create a new meeting every time, instead of using the personal meeting ID), then it would maybe also be nice to have an option to always use the admin account, instead of each individual user's account. This would avoid having to add all users to Zoom, and possibly also work without having a paid subscription.

**Comment by ThiefMaster** [comment]
:+1: on being able to link an admin account to create the meetings.

Would it still be possible to grant the user starting the meeting host permissions in that case? Not sure if zoom allows multiple people with such permissions for a meeting...

**Comment by codemakeshare** [comment]
That's a good question, I'm not super familiar with zoom yet. I guess the problem is, if the bot initiates the new meeting under the admin ID, but the admin doesn't physically attend the meeting, there is no host at all, as even the user who set the meeting is just a "guest". 
I just tried a few things through the browser interface, e.g. creating a new meeting with my admin ID, leaving the meeting, and trying to join with another ID. As I was leaving, it said that I should assign another host to keep the meeting going. If there's nobody else in the meeting at that point, it will terminate the meeting. If there is another user, they will become the new host. Not sure if it will be easily possible to have "host-less" meetings, or, set up the meeting as admin and "hand over" hosting to the user that actually created it, without having the admin actually participating through the plugin.

**Comment by codemakeshare** [comment]
Just did some more digging, and found a possible strategy:
"Join before host" setting: if this is active in the account settings, it is possible to schedule meetings where participants can log on before the host is online. I think this is the most promising way: use the API to schedule a meeting using the admin's credentials, with setting "join before host" = true. Users can have the meeting without the admin ever joining. 
https://support.zoom.us/hc/en-us/articles/202828525-Join-Before-Host
I'd recommend to turn off email notifications in the admin account... Also, it should probably be an optional setting for smaller installations, as there is a 100 meetings/day rate limit. In a 5-user setup, it's not a problem, but maybe not ideal for large organisations.

**Comment by rochaporto** [comment]
In addition to passing a specific meeting ID it could be nice to have 'channel' meetings as well - creating if it doesn't exist. Something like:
```
/zoom start (default to personal ID)
/zoom start SOMEID
/zoom start channel (default to room with channel name)
```

Not sure how easy it would be to create the rooms if they don't exist and handle the meeting room config.

**Comment by ThiefMaster** [comment]
I think with zoombombing being more and more a problem it's becoming even more important to allow creating separate meetings (ideally with a random password included in the link).

**Comment by larkox** [comment]
@aaronrothschild another cherry on top, users could decide what to do by default (personal ID or new meeting) on a user settings panel. `/zoom settings` would open the user settings panel, which will allow him to change this and maybe other future settings (DnD while on a meeting?).

**Comment by aaronrothschild** [comment]
@larkox iagreed, t would be awesome as others have suggested if we could:
- Have a meeting room aligned with a meeting name (ie: "Project A") with a random password each time it is spun up.
- Set that meeting name in the channel settings for "zoom" so it's consistently named whenever I start the meeting

**Comment by larkox** [comment]
@aaronrothschild The "free text input" for settings and flows is already working (even if it needs still to get a bit more mature), so adding a "Default meeting name" associated to user or to channel would be no problem at all.

**Comment by evanractivand** [comment]
We have only a few paid Zoom accounts at our company and it would also be great if we could specify as an admin one specific Zoom account to be used to create meetings by any user who initiates, if possible. Either this could be made the default action or an option when starting a meeting by users, either would be good.
