### ISSUE TITLE
CSRF Header check failed for request

### ISSUE THREAD

**Issue by rterzi** [mattermost/mattermost-plugin-zoom#83]
Mattermost Version: 5.21.0
Database Schema Version: 5.21.0
Zoom Plugin Version: 1.3.0

When setup the plugin, users can't start new meeting, with error:
```
We could not verify your Mattermost account in Zoom. Please ensure that your Mattermost email address matches your Zoom email address.
Zoom error: Invalid access token.
```

Then I've opened debug logging. Result:
```
{"level":"debug","ts":1584971739.7136066,"caller":"mlog/log.go:163","msg":"CSRF Check failed for request - Please migrate your plugin to either send a CSRF Header or Form Field, XMLHttpRequest is deprecated","path":"/plugins/zoom/api/v1/meetings","ip":"xxx.xxx.xxx.xxx:63488","session_id":"mu5nn1chc3fitc*************","user_id":"qzouptumy7dzj8ah***********"}
```

**Comment by larkox** [comment]
@rterzi Thank you for bringing this issue.

I am checking where the problem might be, and I would like to ask you to double check the apiKey being the correct one. Make sure to check any possible space at the end, or similar details.

Thanks!

**Comment by rterzi** [comment]
@larkox you're welcome. I checked it again two times, no change.

**Comment by larkox** [comment]
Would you mind contacting me on [Mattermost Community](https://community.mattermost.com/)? I would like to ask you a few more details about your problem. My username there is `@daniel.espino.garca`.

**Comment by larkox** [comment]
Problem is not about the CSRF, but the plugin not updating the information after a configuration change. This was resolved by disabling and enabling again the plugin, but a better solution would include code changes. A [new issue](https://github.com/mattermost/mattermost-plugin-zoom/issues/86) has been created to solve this problem.

**Comment by mickmister** [comment]
The error from the issue description generated by the Mattermost server `CSRF Check failed for request - Please migrate your plugin to either send a CSRF Header or Form Field, XMLHttpRequest is deprecated`. This should not be occurring since this PR was merged https://github.com/mattermost/mattermost-plugin-zoom/pull/51 .

@rterzi Can you tell me some things about your evironment? Particularly:

- What version of the Zoom plugin are you using?
- What version of Mattermost are you using?
- What is the value of the Mattermost server config value `ServiceSettings.ExperimentalStrictCSRFEnforcement`?

Thanks for using Mattermost and the Zoom plugin @rterzi!

**Comment by mickmister** [comment]
@larkox I think there are two different issues here. The two errors in the issue description should be mutually exclusive.

- The first error implies we got to the plugin's API endpoint and something failed on Zoom's side.
- The second error implies that there was an issue with Mattermost's own CSRF token, and so it did not let the request get to the Zoom plugin. This second issue should not occur, since the issue author is using a release with this PR https://github.com/mattermost/mattermost-plugin-zoom/pull/51. I think this issue should be debugged separately from the first issue.

**Comment by rterzi** [comment]
> * What is the value of the Mattermost server config value `ServiceSettings.ExperimentalStrictCSRFEnforcement`?

```
"ExperimentalStrictCSRFEnforcement": false
```

**Comment by mickmister** [comment]
@crspeller Any thoughts on why we might be getting the CSRF token error without having `ExperimentalStrictCSRFEnforcement` enabled?

**Comment by crspeller** [comment]
@mickmister The setting doesn't turn off the check it just turned off the enforcement of the check. The request will still work but it shows an error message so you can find what is in violation before turning it on.

**Comment by mickmister** [comment]
@crspeller Good to know, though it's still puzzling why the error is showing up if we have the CSRF token being sent properly from the plugin's webapp. It's been set up to send the token with `Client4.getOptions` for quite some time, and is certainly in the release @rterzi is using. Looking at the error message, it is definitely coming from the Zoom plugin too.
